### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Siol-GTM** [davidgamingzz/Lootbox#2]
![image](https://user-images.githubusercontent.com/63442966/82107021-7ac4aa00-96d9-11ea-96f7-203ae6908adf.png)

**Comment by davidgamingzz** [comment]
You must have an older version of InvMenu. Update to the [latest version](https://github.com/Muqsit/InvMenu/).

**Comment by Siol-GTM** [comment]
When right clicking the default lootbox, you get extra item from right clicking it and 3 extra items and that make it 4 items total instead of 3
